---
title: "STAT413 Hmwk9"
output: word_document
---

```{r}
library(tidycensus)
library(tidyverse)
library(dplyr)
library(ggplot2)
```
```{r}
##1. 
census_api_key("7ad943cca8a7dfe1fbdd6ce39241cc823f165b70")
install = TRUE
```
```{r}
##2a
vt <- get_acs(geography = "county", 
              variables = c(medincome = "B01001A_011"), 
              state = "California", 
              year = 2015)

vt
```
```{r}
##2b. 
vt%>%
  filter(estimate>30000)%>%
  arrange(desc(estimate)) -> vt1
vt1
```
```{r}
##2c. 
vt1%>%
  filter(estimate==51644,moe==667) ->vt2
vt2
```
```{r}
##2d. 
vt1%>%
  ggplot(aes(x = estimate))+
  geom_boxplot(color ="black", fill ="red")
```
```{r}
##2e. 
vt1%>%
  mutate(NAME = gsub("County","", NAME)) %>%
  ggplot(aes(x = estimate, y = reorder(NAME, estimate))) +
  geom_errorbarh(aes(xmin = estimate - moe, xmax = estimate + moe)) +
  geom_point(color = "blue", size = 3) +
  labs(title = "Median Income for White Males by County",
       subtitle = "2014-2018 American Community Survey",
       y = "",
       x = "ACS estimate (bars represent margin of error)")
```